name: Upload Chrome Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pack extension into ZIP
        run: zip -r extension.zip . -x "*.git*" ".github/*" "docs/*" "README.md" "wordshk-tools/*" "tests/*" "*.zip"

      - name: Upload to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: 'extension.zip'
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: true
